# Spring settings
spring:
  profiles:
    active: dev

# FFmpeg settings
ffmpeg:
  execPath: /bin/ffmpeg
  probeExecPath: /bin/ffprobe
  norppaUrl: http://ams3-automatic-wtvzn.pukkistream.net:1935/abr/norppalive/live/norppalive_720p/chunks.m3u8
  filePath: /opt/norppabot/norppis.jpg

# Pushover settings
pushover:
  apiToken: xxx
  userToken: xxx
  title: Norppabot

# Twitter settings
twitter:
  consumerKey: xxx
  consumerSecret: xxx
  accessToken: xxx
  accessTokenSecret: xxx
  message: "El√§in havaittu. Onko se norppa? #norppalive #norppa #pullervo"

# Norppis settings
norppis:
  minConfidence: 65
  schedule: 0 */3 6-22 * * *
  messaging:
    enabled: true